name: Generate GitHub Profile Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout profile repository
        uses: actions/checkout@v4

      - name: Generate GitHub stats
        uses: anuraghazra/github-readme-stats@master
        with:
          github_user: rajiratrizer
          show_icons: true
          theme: tokyonight
          hide_border: true
          include_all_commits: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
